export const EMOJI_DATA = {
  "Smileys & Emotion": [
    { name: "Grinning Face", emoji: "😀" },
    { name: "Smiling Face", emoji: "☺️" },
    { name: "Crying Face", emoji: "😢" },
    { name: "Angry Face", emoji: "😠" },
    { name: "Thumbs Up", emoji: "👍" },
    { name: "Thumbs Down", emoji: "👎" },
    { name: "Laughing", emoji: "😄" },
    { name: "Wink", emoji: "😉" },
    { name: "Heart Eyes", emoji: "😍" },
    { name: "Thinking", emoji: "🤔" },
    { name: "Zipped Mouth", emoji: "🤐" },
    { name: "Sleeping", emoji: "😴" },
    { name: "Sick", emoji: "🤒" },
    { name: "Sad", emoji: "☹️" },
    { name: "Scared", emoji: "😨" },
    { name: "Celebrate", emoji: "🥳" }
  ],
  "People & Fantasy": [
    { name: "Person", emoji: "🧑" },
    { name: "Baby", emoji: "👶" },
    { name: "Old Person", emoji: "🧓" },
    { name: "Boy", emoji: "👦" },
    { name: "Girl", emoji: "👧" },
    { name: "Woman", emoji: "👩" },
    { name: "Man", emoji: "👨" },
    { name: "Doctor", emoji: "🧑‍⚕️" },
    { name: "Student", emoji: "🧑‍🎓" },
    { name: "Teacher", emoji: "🧑‍🏫" },
    { name: "Chef", emoji: "🧑‍🍳" },
    { name: "Police Officer", emoji: "👮" },
    { name: "Firefighter", emoji: "👨‍🚒" }
  ],
  "Animals & Nature": [
    { name: "Dog", emoji: "🐶" },
    { name: "Cat", emoji: "🐱" },
    { name: "Mouse", emoji: "🐭" },
    { name: "Hamster", emoji: "🐹" },
    { name: "Rabbit", emoji: "🐰" },
    { name: "Fox", emoji: "🦊" },
    { name: "Bear", emoji: "🐻" },
    { name: "Panda", emoji: "🐼" },
    { name: "Lion", emoji: "🦁" },
    { name: "Cow", emoji: "🐮" },
    { name: "Pig", emoji: "🐷" },
    { name: "Frog", emoji: "🐸" },
    { name: "Monkey", emoji: "🐵" },
    { name: "Chicken", emoji: "🐔" },
    { name: "Penguin", emoji: "🐧" },
    { name: "Sun", emoji: "☀️" },
    { name: "Moon", emoji: "🌙" },
    { name: "Star", emoji: "⭐" },
    { name: "Cloud", emoji: "☁️" },
    { name: "Rain", emoji: "🌧️" }
  ],
  "Food & Drink": [
    { name: "Apple", emoji: "🍎" },
    { name: "Banana", emoji: "🍌" },
    { name: "Grapes", emoji: "🍇" },
    { name: "Strawberry", emoji: "🍓" },
    { name: "Watermelon", emoji: "🍉" },
    { name: "Pizza", emoji: "🍕" },
    { name: "Hamburger", emoji: "🍔" },
    { name: "Fries", emoji: "🍟" },
    { name: "Cookie", emoji: "🍪" },
    { name: "Cake", emoji: "🍰" },
    { name: "Juice", emoji: "🧃" },
    { name: "Milk", emoji: "🥛" },
    { name: "Water", emoji: "💧" },
    { name: "Ice Cream", emoji: "🍦" }
  ],
  "Activities": [
    { name: "Soccer", emoji: "⚽" },
    { name: "Basketball", emoji: "🏀" },
    { name: "Tennis", emoji: "🎾" },
    { name: "Video Game", emoji: "🎮" },
    { name: "Reading", emoji: "📚" },
    { name: "Painting", emoji: "🎨" },
    { name: "Music", emoji: "🎵" },
    { name: "Swimming", emoji: "🏊" },
    { name: "Cycling", emoji: "🚴" },
    { name: "Dancing", emoji: "💃" }
  ],
  "Objects": [
    { name: "Watch", emoji: "⌚" },
    { name: "Mobile Phone", emoji: "📱" },
    { name: "Computer", emoji: "💻" },
    { name: "Keyboard", emoji: "⌨️" },
    { name: "TV", emoji: "📺" },
    { name: "Camera", emoji: "📷" },
    { name: "Flashlight", emoji: "🔦" },
    { name: "Pencil", emoji: "✏️" },
    { name: "Bed", emoji: "🛌" },
    { name: "Toilet", emoji: "🚽" },
    { name: "Shower", emoji: "🚿" },
    { name: "Sofa", emoji: "🛋️" }
  ],
  "Symbols": [
    { name: "Red Heart", emoji: "❤️" },
    { name: "Check Mark", emoji: "✅" },
    { name: "Cross Mark", emoji: "❌" },
    { name: "Exclamation", emoji: "❗" },
    { name: "Question", emoji: "❓" },
    { name: "SOS", emoji: "🆘" }
  ],
  "Tone: Pale": [],
  "Tone: Cream White": [],
  "Tone: Brown": [],
  "Tone: Dark Brown": [],
  "Tone: Black": []
};